[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "6rSij7TX6LCdGcBpyASCYyXf4QXjrW7xLaEApxHiC2e9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/clinton/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
